### PR TITLE
FEATURE: added support for accessKey and secretKey stored as env vari…

### PR DESCRIPTION
**Pull request by seroche**
FEATURE: added support for accessKey and secretKey stored as env variables
FEATURE: added support of codes ran within an ECS container
FEATURE: made CreateFileSystem async

### CODE REVIEW

**Comment by seroche** [comment]
I tested the following use cases:
- Define `profileName`
- Define `accessKey` and `secretKey`
- Define `profileName` and `accessKey` and `secretKey` at the same time
- Assume IAM role

It looks fine to me. I will test the ECS behavior once you publish a new version. It will automatically be downloaded within my CI flow.

**Comment by emgarten** [comment]
@seroche thank you for the PR, this looks like a great approach for detecting the AWS environment while still keeping the same behavior for existing scenarios.

The work to make CreateFileSystemAsync looks great as well, thanks for fixing up the tests. I appreciate the effort here. 💯

**Comment by seroche** [comment]
My pleasure! Do you have CI/CD flow auto publishing a new version?

**Comment by emgarten** [comment]
CI/CD will auto push the new packages to https://nuget.blob.core.windows.net/packages/index.json

Releasing to nuget.org is automated, but a manual decision so that not all builds get pushed there. The build seems to be running slow at the moment, but I'll release the new build to nuget.org tomorrow if all end to end tests pass.

**Comment by emgarten** [comment]
@seroche this change is available in https://www.nuget.org/packages/Sleet/3.0.13

**Comment by emgarten** [comment]
Thanks again for the work on this 🍰

**Pull request merged**
