### PR TITLE
Use GetCallerIdentityAsync

### PR DESCRIPTION
**Pull request by iainb123**
@medianotion can you give this a go?  This still works for the simple EC2 case I use.

### CODE REVIEW

**Comment by emgarten** [comment]
This looks like a better way of handling the credential check to me.

I'll wait for @medianotion to try it out before merging it incase it needs additional changes.

**Comment by medianotion** [comment]
I will try in the next couple days.  Its not as simple as compiling and dropping it on an EC2 instance.  This is on CodeBuild which stands up a new container.  I would have to download to that container during the build script.  Its not hard but I have to focus on my work right now.

**Comment by emgarten** [comment]
I think this change is worth taking either way, I'm going to merge it. @medianotion let us know once you try it out and we can continue to improve this for AWS.

**Comment by emgarten** [comment]
This PR has been released in https://www.nuget.org/packages/Sleet/3.0.6

**Comment by medianotion** [comment]
This worked for me.  Thank you everyone!

**Comment by emgarten** [comment]
@iainb123 thanks for all the hard work on this!

**Pull request merged**
