### PR TITLE
Fix path to Sleet.exe from props

### PR DESCRIPTION
**Pull request by kzu**
Since the props is imported from build\net46\Sleep.props, this should have been ..\..\tools\Sleet.exe

### CODE REVIEW

**Comment by emgarten** [comment]
Thanks for the fix! :cake:

**Comment by kzu** [comment]
public version still broken, any chance you can push an update plz?

Thanks!

**Comment by emgarten** [comment]
I'll update it

**Comment by emgarten** [comment]
https://www.nuget.org/packages/Sleet/ 2.1.0 is available now

**Pull request merged**
