### PR TITLE
Weird path behavior on sub feeds fix

### PR DESCRIPTION
**Pull request by jcagme**
Most likely there is a cleaner/easier way to do it.

### CODE REVIEW

**Comment by emgarten** [comment]
I think BaseURI should probably contain the full path, and the file system should handle that so that URI mangling is easier.

I appreciate the PR! I probably regressed this when I fixed the physical system to handle sub feeds. So let me take another look at this.

**Comment by emgarten** [comment]
I have a fix here: https://github.com/emgarten/Sleet/commit/51b0b8b0b739e17a18627003358d18a3e84e6956

It adds validation to ensure that BaseURI contains the sub feed path, and uses the container URI to create relative paths instead of BaseURI.

**Comment by emgarten** [comment]
Are more changes needed? Otherwise I think this can be closed

**Comment by jcagme** [comment]
Nope, closing PR

**Pull request closed without merging**
