### PR TITLE
new s3 url requirements

### PR DESCRIPTION
**Pull request by nothingalike**
Using the S3 approach I noticed that the S3 url it was using to construct my nuget location was incorrect. I was constantly getting a 403 which gave the details of the new S3 url structure.

### CODE REVIEW

**Comment by emgarten** [comment]
Thanks for the PR @nothingalike, I appreciate it!

I'm not an expert on S3, but looking at the docs it reads like both styles should work: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

It looks like the PR moves from *path-style* to *virtual-hosted-style*. Do you know why *path-style* doesn't work for you? The docs don't mention either format as the one that works everywhere, or the new format. 

Any help on this is appreciated, I just want to make sure others are not broken by this change. Or if needed that we add a config switch for it. If it wasn't working for you then it sounds like some fix is needed.

/cc @skarllot who added S3 support originally

**Comment by nothingalike** [comment]
hmm, thats a good question. i can look into PS vs VHS. I was just hitting a wall of 403's with S3 telling me to use a new url structure.

**Comment by emgarten** [comment]
@nothingalike any luck finding why your feed gives you 403s for the current url structure?

If needed we can just add an option to sleet.json for AWS feeds to allow changing this.

**Comment by nothingalike** [comment]
@emgarten hmm, yeah if we just had the ability to toggle format of our url type, I believe that would be a good solution. keeps things flexible imo

**Comment by emgarten** [comment]
@nothingalike this would be an easy change, instead of changing GetBucketPath, add a second utility method to get the virtual-hosted-style URL. This method is only used when setting up the file system, which is the same time the local settings file is read.

So if you check for a bool in the config under AWS feeds you can then call whichever method here: https://github.com/emgarten/Sleet/blob/457380582c47808e187f8d70ccfa38924bc621d8/src/SleetLib/FileSystem/FileSystemFactory.cs#L130

**Comment by emgarten** [comment]
@nothingalike do you have another PR coming for this? Or were you able to track down the cause?

**Pull request closed without merging**
